### ISSUE TITLE
Write issues with certification for Mr. White.

### ISSUE THREAD

**Issue by Apptimize-AB** [igovdirect/iOS#9]

**Comment by Mr-Pink-iGov-Direct** [comment]
Issues when trying to archive the application in Xcode.
When running the application on a simulator everything works ok but I try to archive it on "Generic iOS Device" Xcode complains.
![skarmavbild 2016-11-21 kl 13 36 47](https://cloud.githubusercontent.com/assets/21218752/20483107/a307621a-aff0-11e6-9d6e-42858ec0b4b7.png)

This issue only appears when trying to archive it on a "Generic iOS Device".

Second issue is that I am not sure that all the certifications, provisioning profiles and all of the other iTunes Connect related things are correct.

I have reached the point where i need to select "which version to test" in TestFlight.
Archiving the application is a must to be able to select which version to test.

**Comment by Mr-White-iGov-Direct** [comment]
I need an developer account to test provisioning profile. 
Which Swift version you're using? Which XCode version you're using?

**Comment by Apptimize-AB** [comment]
Swift 3.0 and Xcode 8.1. I will send you an invite.
